# Generated by Django 4.0.2 on 2024-09-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tagpost_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
